# -*- coding: utf-8 -*-
"""minipro_ovarian_cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bmmEfRYaBYBgPNnPs5gqk9xsBCUqndzf
"""

import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense
import os
import kagglehub
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df1=pd.read_csv("/content/Supplementary data 1.csv")
df2=pd.read_csv("/content/Supplementary data 2.csv")
df3=pd.read_csv("/content/Supplementary data 3.csv")
df4=pd.read_csv("/content/Supplementary data 4.csv")
df5=pd.read_csv("/content/Supplementary data 5.csv")

df1.head()

df2.head()

df3.head()

df4.head()

df5.head()

df = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)
df.to_csv("data.csv")

df = df.drop(columns=['Unnamed: 0', 'SUBJECT_ID', 'Biomarker', 'Biomarker Name'], errors='ignore')


for col in df.columns:
    # Convert everything to string first
    df[col] = df[col].astype(str)

    # Remove tab characters and extra spaces
    df[col] = df[col].str.replace('\t', '', regex=False).str.strip()

    # Replace empty strings with NaN
    df[col] = df[col].replace(['', 'nan', 'None'], np.nan)

    # Convert to numeric (except target if categorical)
    if col != 'TYPE':
        df[col] = pd.to_numeric(df[col], errors='coerce')

print("Cleaning completed.")
print(df.info())

df = df.dropna(subset=['TYPE'])

df = df.drop(columns=['CA72-4'])  # since 762 missing

df = df.fillna(df.median(numeric_only=True))

df.head()

df['TYPE'] = pd.to_numeric(df['TYPE'], errors='coerce')

df['TYPE'] = df['TYPE'].astype(int)

print(df['TYPE'].value_counts())

print(df['TYPE'].value_counts(normalize=True)*100)

df['TYPE'].value_counts().plot(kind='bar')
plt.title("Class Distribution")
plt.xlabel("Cancer Type")
plt.ylabel("Count")
plt.show()

print(df['TYPE'].unique())

df.groupby('TYPE')[['CA125','HE4']].mean()

sns.boxplot(x='TYPE', y='CA125', data=df)
plt.title("CA125 Distribution by Cancer Type")
plt.show()

sns.boxplot(x='TYPE', y='HE4', data=df)
plt.title("HE4 Distribution by Cancer Type")
plt.show()

corr = df[['CA125', 'HE4', 'TYPE']].corr()
print(corr)

sns.heatmap(df[['CA125', 'HE4', 'TYPE']].corr(), annot=True, cmap='coolwarm')
plt.title("Correlation between Biomarkers and Cancer Type")
plt.show()

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = df.drop(columns=['TYPE'])
y = df['TYPE']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

importance = pd.Series(model.feature_importances_, index=X.columns)

importance = importance.sort_values(ascending=False)

print(importance.head(15))

importance.head(10).plot(kind='bar')
plt.title("Top Biomarkers for Ovarian Cancer Prediction")
plt.xlabel("Biomarkers")
plt.ylabel("Importance Score")
plt.show()

y_prob_model = model.predict_proba(X_test)[:,1]

ca125_scores = X_test['CA125']
he4_scores = X_test['HE4']

from sklearn.metrics import roc_curve, auc

fpr_ca125, tpr_ca125, _ = roc_curve(y_test, ca125_scores)
auc_ca125 = auc(fpr_ca125, tpr_ca125)

fpr_he4, tpr_he4, _ = roc_curve(y_test, he4_scores)
auc_he4 = auc(fpr_he4, tpr_he4)

fpr_model, tpr_model, _ = roc_curve(y_test, y_prob_model, pos_label=1)
auc_model = auc(fpr_model, tpr_model)

plt.figure()

plt.plot(fpr_ca125, tpr_ca125, label=f'CA125 (AUC = {auc_ca125:.2f})')
plt.plot(fpr_he4, tpr_he4, label=f'HE4 (AUC = {auc_he4:.2f})')
plt.plot(fpr_model, tpr_model, label=f'ML Model (AUC = {auc_model:.2f})')

plt.plot([0,1],[0,1], '--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison: CA125 vs HE4 vs ML Model")

plt.legend()
plt.show()

import shap

explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(X_test)

if isinstance(shap_values, list):
    shap_values = shap_values[1]

shap.summary_plot(shap_values, X_test)

shap_values = explainer.shap_values(X_test)[:,:,1]

print("X_test shape:", X_test.shape)
print("SHAP shape:", shap_values.shape)

shap.summary_plot(shap_values, X_test)

shap.summary_plot(shap_values, X_test, plot_type="bar")

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

# -------------------------------
# Define Models
# -------------------------------
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(probability=True),
    "KNN": KNeighborsClassifier()
}

results = []

# -------------------------------
# Train & Evaluate
# -------------------------------
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    results.append([name, acc, prec, rec, f1])

# -------------------------------
# Create Comparison Table
# -------------------------------
results_df = pd.DataFrame(results, columns=[
    "Model", "Accuracy", "Precision", "Recall", "F1 Score"
])

print("\nModel Comparison:\n")
print(results_df)

# Sort by F1 Score (best metric for imbalance)
results_df = results_df.sort_values(by="F1 Score", ascending=False)

print("\nBest Model:\n")
print(results_df.iloc[0])

import matplotlib.pyplot as plt

results_df.set_index("Model")[["Accuracy", "Recall", "F1 Score"]].plot(kind="bar")
plt.title("Model Performance Comparison")
plt.ylabel("Score")
plt.xticks(rotation=45)
plt.show()

best_model_name = results_df.iloc[0]["Model"]
best_model = models[best_model_name]

print(f"\nBest Model Selected: {best_model_name}")

model = RandomForestClassifier(class_weight='balanced')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test, model.predict_proba(X_test)[:,1])

print(best_model.predict_proba(new_data))

test_cases = [
    {'CA125': 30, 'HE4': 50},   # likely normal
    {'CA125': 120, 'HE4': 150}, # borderline
    {'CA125': 500, 'HE4': 300}  # high risk
]

for case in test_cases:
    new_data = pd.DataFrame([case])

    for col in X.columns:
        if col not in new_data.columns:
            new_data[col] = 0

    new_data = new_data[X.columns]

    pred = best_model.predict(new_data)[0]
    prob = best_model.predict_proba(new_data)[0][1]

    print(case, "→", pred, prob)

new_data = pd.DataFrame([X.mean()])  # realistic baseline

new_data = new_data.fillna(df.median())

new_data = scaler.transform(new_data)

RandomForestClassifier(max_depth=5)

y_pred = best_model.predict(X_test)
y_prob = best_model.predict_proba(X_test)[:, 1]

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Model Performance on Test Data:\n")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import roc_auc_score, roc_curve

auc_score = roc_auc_score(y_test, y_prob)
print(f"\nROC-AUC Score: {auc_score:.4f}")

fpr, tpr, _ = roc_curve(y_test, y_prob)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {auc_score:.2f}")
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

results = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred,
    "Probability": y_prob
})

print("\nSample Predictions:\n")
print(results.head(10))

print("\nUnique Probabilities:\n")
print(pd.Series(y_prob).round(2).value_counts().head(10))

# Start with realistic baseline (VERY IMPORTANT)
new_data = pd.DataFrame([X.mean()])

# Modify only important features
new_data['CA125'] = 120
new_data['HE4'] = 150

new_data = scaler.transform(new_data)

best_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=5,              # prevents overconfidence
    min_samples_leaf=5,       # smoother predictions
    class_weight='balanced',
    random_state=42
)

from sklearn.calibration import CalibratedClassifierCV

calibrated_model = CalibratedClassifierCV(best_model, method='sigmoid', cv=5)
calibrated_model.fit(X_train, y_train)

y_prob = calibrated_model.predict_proba(X_test)[:,1]

prediction = calibrated_model.predict(new_data)[0]
probability = calibrated_model.predict_proba(new_data)[0][1]

probability = max(0.01, min(0.99, probability))

threshold = 0.5   # more sensitive for cancer detection
prediction = (probability > threshold)

print("New Probability:", probability)

# Create realistic input
new_data = pd.DataFrame([X.mean()])
new_data['CA125'] = 120
new_data['HE4'] = 150

# Scale
new_data = scaler.transform(new_data)

# Predict
probability = calibrated_model.predict_proba(new_data)[0][1]

# Clip
probability = max(0.01, min(0.99, probability))

# Threshold
prediction = 1 if probability > 0.5 else 0

# Output
if prediction == 1:
    print(f"Cancer Risk Detected (Probability: {probability:.2f})")
else:
    print(f"Low Risk (Probability: {probability:.2f})")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Predictions on test data
y_pred = calibrated_model.predict(X_test)
y_prob = calibrated_model.predict_proba(X_test)[:, 1]

# Metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("\nModel Performance:\n")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt

# Your metrics
metrics = {
    "Accuracy": 0.9358,
    "Precision": 0.8922,
    "Recall": 0.9891,
    "F1 Score": 0.9381
}

# Extract keys and values
names = list(metrics.keys())
values = list(metrics.values())

# Plot
plt.figure()
plt.bar(names, values)

plt.ylim(0, 1)
plt.xlabel("Metrics")
plt.ylabel("Score")
plt.title("Model Performance")

# Show values on bars
for i, v in enumerate(values):
    plt.text(i, v + 0.01, f"{v:.2f}", ha='center')

plt.show()

plt.figure()
plt.plot(names, values, marker='o')

plt.ylim(0, 1)
plt.xlabel("Metrics")
plt.ylabel("Score")
plt.title("Model Performance Trend")

# Annotate values
for i, v in enumerate(values):
    plt.text(i, v + 0.01, f"{v:.2f}", ha='center')

plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test, y_prob)
print(f"\nROC-AUC Score: {auc:.4f}")